[build-system]
requires = ["setuptools>=42", "wheel", "torch"]
build-backend = "setuptools.build_meta"

[project]
name = "packkv_cuda"
version = "0.1.0"
description = "CUDA extension for PackKV"
requires-python = ">=3.7" 